// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ZewhKeZmEh00uSOh1bx-aid8OziF8zw',
    appId: '1:249692298052:web:a864456fffe0ebe7859511',
    messagingSenderId: '249692298052',
    projectId: 'eduflow-57ff9',
    authDomain: 'eduflow-57ff9.firebaseapp.com',
    storageBucket: 'eduflow-57ff9.firebasestorage.app',
    measurementId: 'G-PMY5TEMD56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPOkY4JZiM97NvDUOXa_FAFEtnD4ep67A',
    appId: '1:249692298052:android:bf3af007544eae68859511',
    messagingSenderId: '249692298052',
    projectId: 'eduflow-57ff9',
    storageBucket: 'eduflow-57ff9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ZewhKeZmEh00uSOh1bx-aid8OziF8zw',
    appId: '1:249692298052:web:1fc63746bb18b354859511',
    messagingSenderId: '249692298052',
    projectId: 'eduflow-57ff9',
    authDomain: 'eduflow-57ff9.firebaseapp.com',
    storageBucket: 'eduflow-57ff9.firebasestorage.app',
    measurementId: 'G-REQQ1J9S0V',
  );

}